# queue for generating all protxlstm embs

export CUDA_VISIBLE_DEVICES=0

### GB1 ###

python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --embed_folder="embs_max_seq_100" --max_context_sequences=100 --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --embed_folder="embs_max_seq_50" --max_context_sequences=50 --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/gb1/sampled.csv" --embed_folder="embs_max_seq_0" --max_context_sequences=0 --msa_path="msas/individual_msas/proeng/gb1_trunc/gb1_trunc_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

### AAV ###

python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=0 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=12345 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=35 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=444 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42


python  run_pregen_emb.py  --dataset_path="data/proeng/aav/two_vs_many.csv" --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --embed_folder="embs_max_seq_100" --max_context_sequences=100 --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --embed_folder="embs_max_seq_50" --max_context_sequences=50 --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/aav/two_vs_many.csv" --embed_folder="embs_max_seq_0" --max_context_sequences=0 --msa_path="msas/individual_msas/proeng/aav/aav_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --yield_no_context=True --is_mutation=True --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42



### thermo ###

python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42


python  run_pregen_emb.py  --dataset_path="data/proeng/thermo/mixed_split.csv" --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --embed_folder="embs_max_seq_100" --max_context_sequences=100 --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --embed_folder="embs_max_seq_50" --max_context_sequences=50 --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/proeng/thermo/mixed_split.csv" --embed_folder="embs_max_seq_0" --max_context_sequences=0 --msa_path="msas/individual_msas/proeng/thermo/thermo_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42


# ### Subcellular Localization ### 

python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42


python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --embed_folder="embs_max_seq_100" --max_context_sequences=100 --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --embed_folder="embs_max_seq_50" --max_context_sequences=50 --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42
python  run_pregen_emb.py --dataset_path="data/annotation/scl/balanced.csv" --embed_folder="embs_max_seq_0" --max_context_sequences=0 --msa_path="msas/individual_msas/annotation/scl/annotation_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42

### SS3 ###

export STEP=0
for i in 12; do
    echo "Processing Layer ${i} to $((i + $STEP))"

    echo "embeddings-rand/seed-0/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param=True --embed_torch_seed=0 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    
    echo "embeddings-rand/seed-12345/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param=True --embed_torch_seed=12345 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    
    echo "embeddings-rand/seed-42/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param=True --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    
    echo "embeddings-rand/seed-35/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param=True --embed_torch_seed=35 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "embeddings-rand/seed-444/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param=True --embed_torch_seed=444 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "embeddings-stat/seed-0/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --resample_param=True --embed_torch_seed=0 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    
    echo "embeddings-stat/seed-12345/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --resample_param=True --embed_torch_seed=12345 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "embeddings-stat/seed-42/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --resample_param=True --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    
    echo "embeddings-stat/seed-35/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --resample_param=True --embed_torch_seed=35 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "embeddings-stat/seed-444/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --resample_param=True --embed_torch_seed=444 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    
    echo "intra_seq"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="intra_seq" --embed_torch_seed=0 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="intra_seq" --embed_torch_seed=12345 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="intra_seq" --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="intra_seq" --embed_torch_seed=35 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="intra_seq" --embed_torch_seed=444 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "inter_seq"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="inter_seq" --embed_torch_seed=0 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="inter_seq" --embed_torch_seed=12345 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="inter_seq" --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="inter_seq" --embed_torch_seed=35 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --reset_param="inter_seq" --embed_torch_seed=444 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "embeddings/seed-42/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "max_nseq_100"
    echo "embeddings/seed-42/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --embed_folder="embs_max_seq_100" --max_context_sequences=100 --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "max_nseq_50"
    echo "embeddings/seed-42/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --embed_folder="embs_max_seq_50" --max_context_sequences=50 --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

    echo "max_nseq_0"
    echo "embeddings/seed-42/"
    python  run_pregen_emb.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --embed_folder="embs_max_seq_0" --max_context_sequences=0 --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

done

export STEP=1
export i=0
echo "Processing Layer ${i} to $((i + $STEP))"
echo "embeddings/seed-42/"
python  run_pregen_emb.py --embed_folder="embeddings_01" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

export i=2
echo "Processing Layer ${i} to $((i + $STEP))"
echo "embeddings/seed-42/"
python  run_pregen_emb.py --embed_folder="embeddings_23" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

export i=4
echo "Processing Layer ${i} to $((i + $STEP))"
echo "embeddings/seed-42/"
python  run_pregen_emb.py --embed_folder="embeddings_45" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

export i=6
echo "Processing Layer ${i} to $((i + $STEP))"
echo "embeddings/seed-42/"
python  run_pregen_emb.py --embed_folder="embeddings_67" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

export i=8
echo "Processing Layer ${i} to $((i + $STEP))"
echo "embeddings/seed-42/"
python  run_pregen_emb.py --embed_folder="embeddings_89" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42

export i=10
echo "Processing Layer ${i} to $((i + $STEP))"
echo "embeddings/seed-42/"
python  run_pregen_emb.py --embed_folder="embeddings_1011" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path="msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --max_context_length=145_000 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))" --subset_list='["train","val","cb513","ts115","casp12"]' --embed_batch_size=1 --sampling_seed=42


### Remote homology ###

python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param=True --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --resample_param=True --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'

python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="intra_seq" --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'

python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=0 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=12345 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=35 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --reset_param="inter_seq" --embed_torch_seed=444 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'


python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --embed_folder="embs_max_seq_100" --max_context_sequences=100 --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --embed_folder="embs_max_seq_50" --max_context_sequences=50 --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
python  run_pregen_emb.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --embed_folder="embs_max_seq_0" --max_context_sequences=0 --msa_path="msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap" --encoder_name="poet_201M" --checkpoint=1 --flatten_emb="mean" --embed_torch_seed=42 --max_context_length=145_000 --embed_batch_size=1 --sampling_seed=42 --subset_list='["train","val","test_family_holdout","test_superfamily_holdout","test_fold_holdout"]'
