# queue for running all pytorch models from embs

export CUDA_VISIBLE_DEVICES=0

### Subcellular Localization ###

python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param=True --embed_torch_seed=0 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --resample_param=True --embed_torch_seed=0 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param=True --embed_torch_seed=12345 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --resample_param=True --embed_torch_seed=12345 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param=True --embed_torch_seed=42 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --resample_param=True --embed_torch_seed=42 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param=True --embed_torch_seed=35 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --resample_param=True --embed_torch_seed=35 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param=True --embed_torch_seed=444 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --resample_param=True --embed_torch_seed=444 --sampling_seed=42 --if_rerun_layer=True

python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="intra_seq" --embed_torch_seed=0 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="intra_seq" --embed_torch_seed=12345 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="intra_seq" --embed_torch_seed=42 --sampling_seed=42 # --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="intra_seq" --embed_torch_seed=35 --sampling_seed=42 # --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="intra_seq" --embed_torch_seed=444 --sampling_seed=42 # --if_rerun_layer=True

python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="inter_seq" --embed_torch_seed=0 --sampling_seed=42 # --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="inter_seq" --embed_torch_seed=12345 --sampling_seed=42 # --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="inter_seq" --embed_torch_seed=42 --sampling_seed=42 # --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="inter_seq" --embed_torch_seed=35 --sampling_seed=42 # --if_rerun_layer=True
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --reset_param="inter_seq" --embed_torch_seed=444 --sampling_seed=42 # --if_rerun_layer=True


python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --embed_torch_seed=42 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --embed_folder="embs_max_seq_100" --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100" --all_result_folder="results/pytorch-poet-maxseq_100" --embed_torch_seed=42 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --embed_folder="embs_max_seq_50" --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50" --all_result_folder="results/pytorch-poet-maxseq_50" --embed_torch_seed=42 --sampling_seed=42 --if_rerun_layer=True
python run_protran_pytorch.py --embed_folder="embs_max_seq_0" --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --epochs=750 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0" --all_result_folder="results/pytorch-poet-maxseq_0" --embed_torch_seed=42 --sampling_seed=42 --if_rerun_layer=True


python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_0" --test_embed_folder="embs_max_seq_50" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_50" --all_result_folder="results/pytorch-poet-maxseq_0_50" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_0" --test_embed_folder="embs_max_seq_100" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_100" --all_result_folder="results/pytorch-poet-maxseq_0_100" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_0" --test_embed_folder="embeddings" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_200" --all_result_folder="results/pytorch-poet-maxseq_0_200" --sampling_seed=42

python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_50" --test_embed_folder="embs_max_seq_0" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_0" --all_result_folder="results/pytorch-poet-maxseq_50_0" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_50" --test_embed_folder="embs_max_seq_100" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_100" --all_result_folder="results/pytorch-poet-maxseq_50_100" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_50" --test_embed_folder="embeddings" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_200" --all_result_folder="results/pytorch-poet-maxseq_50_200" --sampling_seed=42

python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_100" --test_embed_folder="embs_max_seq_0" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_0" --all_result_folder="results/pytorch-poet-maxseq_100_0" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_100" --test_embed_folder="embs_max_seq_50" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_50" --all_result_folder="results/pytorch-poet-maxseq_100_50" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embs_max_seq_100" --test_embed_folder="embeddings" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_200" --all_result_folder="results/pytorch-poet-maxseq_100_200" --sampling_seed=42

python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_0" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_0" --all_result_folder="results/pytorch-poet-maxseq_200_0" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_50" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_50" --all_result_folder="results/pytorch-poet-maxseq_200_50" --sampling_seed=42
python run_protran_pytorch.py --dataset_path="data/annotation/scl/balanced.csv" --msa_path='msas/individual_msas/annotation/scl/annotation_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --embed_torch_seed=42 --epochs=750 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_100" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_100" --all_result_folder="results/pytorch-poet-maxseq_200_100" --sampling_seed=42



### SS3 ###


export STEP=0
for i in 12; do
    echo "Processing Layer ${i} to $((i + $STEP))"

    echo "embeddings-rand/seed-0/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=0 --reset_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-rand/seed-12345/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=12345 --reset_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    
    echo "embeddings-rand/seed-42/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --reset_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    
    echo "embeddings-rand/seed-35/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=35 --reset_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-rand/seed-444/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=444 --reset_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-stat/seed-0/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=0 --resample_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-stat/seed-12345/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=12345 --resample_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-stat/seed-42/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --resample_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-stat/seed-35/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=35 --resample_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings-stat/seed-444/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=444 --resample_param=True --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    
    echo "intra_seq"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=0 --reset_param="intra_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=12345 --reset_param="intra_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --reset_param="intra_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=35 --reset_param="intra_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=444 --reset_param="intra_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "inter_seq"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=0 --reset_param="inter_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=12345 --reset_param="inter_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --reset_param="inter_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=35 --reset_param="inter_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=444 --reset_param="inter_seq" --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "embeddings/seed-42/" # DO NOT DELETE
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "max nseq 100" # DO NOT DELETE
    echo "embeddings/seed-42/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_100" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100" --all_result_folder="results/pytorch-poet-maxseq_100" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "max nseq 50" # DO NOT DELETE
    echo "embeddings/seed-42/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_50" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50" --all_result_folder="results/pytorch-poet-maxseq_50" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "max nseq 0" # DO NOT DELETE
    echo "embeddings/seed-42/"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_0" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0" --all_result_folder="results/pytorch-poet-maxseq_0" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

done

export STEP=1

export i=0
echo "Processing Layer ${i} to $((i + $STEP))"

echo "embeddings/seed-42/" # 0 1
python run_protran_pytorch.py --embed_folder="embeddings_01" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

export i=2 # 2 3
echo "Processing Layer ${i} to $((i + $STEP))"

echo "embeddings/seed-42/"
python run_protran_pytorch.py --embed_folder="embeddings_23" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

export i=4 # 4 5
echo "Processing Layer ${i} to $((i + $STEP))"

echo "embeddings/seed-42/"
python run_protran_pytorch.py --embed_folder="embeddings_45" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

export i=6 # 6 7
echo "Processing Layer ${i} to $((i + $STEP))"

echo "embeddings/seed-42/"
python run_protran_pytorch.py --embed_folder="embeddings_67" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

export i=8 # 8 9
echo "Processing Layer ${i} to $((i + $STEP))"

echo "embeddings/seed-42/"
python run_protran_pytorch.py --embed_folder="embeddings_89" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

export i=10 # 10 11
echo "Processing Layer ${i} to $((i + $STEP))"

echo "embeddings/seed-42/"
python run_protran_pytorch.py --embed_folder="embeddings_1011" --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"


export STEP=0
for i in 12; do
    echo "Processing Layer ${i} to $((i + $STEP))"

    echo "max len 0" # DO NOT DELETE
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_0" --test_embed_folder="embs_max_seq_50" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_50" --all_result_folder="results/pytorch-poet-maxseq_0_50" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_0" --test_embed_folder="embs_max_seq_100" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_100" --all_result_folder="results/pytorch-poet-maxseq_0_100" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_0" --test_embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_200" --all_result_folder="results/pytorch-poet-maxseq_0_200" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "max len 50" # DO NOT DELETE
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_50" --test_embed_folder="embs_max_seq_0" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_0" --all_result_folder="results/pytorch-poet-maxseq_50_0" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_50" --test_embed_folder="embs_max_seq_100" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_100" --all_result_folder="results/pytorch-poet-maxseq_50_100" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_50" --test_embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_200" --all_result_folder="results/pytorch-poet-maxseq_50_200" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "max len 100" # DO NOT DELETE
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_100" --test_embed_folder="embs_max_seq_0" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_0" --all_result_folder="results/pytorch-poet-maxseq_100_0" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_100" --test_embed_folder="embs_max_seq_50" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_50" --all_result_folder="results/pytorch-poet-maxseq_100_50" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embs_max_seq_100" --test_embed_folder="embeddings" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_200" --all_result_folder="results/pytorch-poet-maxseq_100_200" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

    echo "max len 200" # DO NOT DELETE
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_0" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_0" --all_result_folder="results/pytorch-poet-maxseq_200_0" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_50" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_50" --all_result_folder="results/pytorch-poet-maxseq_200_50" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"
    python run_protran_pytorch.py --dataset_path="data/structure/secondary_structure/tape_ss3_processed.csv" --msa_path='msas/individual_msas/structure/secondary_structure/tape_ss3_processed/tape_ss3_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_torch_seed=42 --embed_batch_size=1 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_100" --loader_batch_size=120 --epochs=100 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_100" --all_result_folder="results/pytorch-poet-maxseq_200_100" --sampling_seed=42 --manual_layer_min="${i}" --manual_layer_max="$((i + $STEP))"

done


# Remote Homology


python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=0 --reset_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=0 --resample_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=12345 --reset_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=12345 --resample_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=42 --reset_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=42 --resample_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=35 --reset_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=35 --resample_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=444 --reset_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=444 --resample_param=True --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12

python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=0 --reset_param="intra_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=12345 --reset_param="intra_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=42 --reset_param="intra_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=35 --reset_param="intra_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=444 --reset_param="intra_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12

python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=0 --reset_param="inter_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=12345 --reset_param="inter_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=42 --reset_param="inter_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=35 --reset_param="inter_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet"  --embed_torch_seed=444 --reset_param="inter_seq" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12


python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --embed_folder="embeddings" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet" --all_result_folder="results/pytorch-poet" --checkpoint=1 --sampling_seed=42 --if_rerun_layer=True 

echo "large poet max seq len"

python run_protran_pytorch.py --embed_folder="embs_max_seq_100" --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100" --all_result_folder="results/pytorch-poet-maxseq_100" --checkpoint=1 --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --embed_folder="embs_max_seq_50" --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50" --all_result_folder="results/pytorch-poet-maxseq_50" --checkpoint=1 --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --embed_folder="embs_max_seq_0" --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0" --all_result_folder="results/pytorch-poet-maxseq_0" --checkpoint=1 --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12


python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_0" --test_embed_folder="embs_max_seq_50" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_50" --all_result_folder="results/pytorch-poet-maxseq_0_50" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_0" --test_embed_folder="embs_max_seq_100" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_100" --all_result_folder="results/pytorch-poet-maxseq_0_100" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_0" --test_embed_folder="embeddings" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_0_200" --all_result_folder="results/pytorch-poet-maxseq_0_200" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12

python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_50" --test_embed_folder="embs_max_seq_0" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_0" --all_result_folder="results/pytorch-poet-maxseq_50_0" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_50" --test_embed_folder="embs_max_seq_100" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_100" --all_result_folder="results/pytorch-poet-maxseq_50_100" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_50" --test_embed_folder="embeddings" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_50_200" --all_result_folder="results/pytorch-poet-maxseq_50_200" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12

python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_100" --test_embed_folder="embs_max_seq_0" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_0" --all_result_folder="results/pytorch-poet-maxseq_100_0" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_100" --test_embed_folder="embs_max_seq_50" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_50" --all_result_folder="results/pytorch-poet-maxseq_100_50" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embs_max_seq_100" --test_embed_folder="embeddings" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_100_200" --all_result_folder="results/pytorch-poet-maxseq_100_200" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12

python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_0" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_0" --all_result_folder="results/pytorch-poet-maxseq_200_0" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_50" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_50" --all_result_folder="results/pytorch-poet-maxseq_200_50" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
python run_protran_pytorch.py --dataset_path="data/evolution/remote_homology/tape_rh_processed.csv" --msa_path='msas/individual_msas/evolution/remote_homology/tape_rh_processed_memmap' --encoder_name="poet_201M" --checkpoint=1 --embed_batch_size=1 --flatten_emb="mean" --loader_batch_size=256 --learning_rate=1e-5 --epochs=500 --embed_folder="embeddings" --test_embed_folder="embs_max_seq_100" --all_plot_folder="results/pytorch_learning_curves-poet-maxseq_200_100" --all_result_folder="results/pytorch-poet-maxseq_200_100" --sampling_seed=42 --if_rerun_layer=True --manual_layer_min=12 --manual_layer_max=12
